### NUMPY-ARRAY-CREATING-USING-FUNCTION

In [13]:
import numpy as np

### 1-Zeros

In [14]:
arr=np.zeros(4)
arr

array([0., 0., 0., 0.])

### 2-Ones

In [15]:
arr=np.ones(4)
arr

array([1., 1., 1., 1.])

### 3-eye

In [16]:
arr=np.eye(4)    # Diagnal all values will be 1
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 4-Diag

In [17]:
arr=np.diag([1,2,3,5])   
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 5]])

In [18]:
# Find the Diag of an array
np.diag(arr)

array([1, 2, 3, 5])

### 5-Randint

In [19]:
rand_arr=np.random.randint(1,15,4)
rand_arr

array([14,  9, 14, 14])

### 6-Rand

In [20]:
rand_arr=np.random.rand(1,15)
rand_arr

array([[0.44952747, 0.7259258 , 0.7655184 , 0.94353284, 0.51536049,
        0.20531052, 0.52093762, 0.53520106, 0.429035  , 0.27844128,
        0.04220418, 0.31907411, 0.41133259, 0.69916513, 0.36832812]])

### 7-Randn

In [21]:
rand_arr=np.random.randn(15)
rand_arr

array([ 0.47422192,  0.29829811, -1.36652393, -0.76265683,  1.09472439,
       -0.7415213 , -0.1600582 ,  0.64440052,  1.01157029, -0.5348341 ,
       -0.69269009,  0.93716394,  0.34147031, -0.19722893,  0.09046656])

### 