### INDEXING-AND-SLICING-IN-1-D-ARRAY

In [11]:
# import numpy library
import numpy as np

In [12]:
# Creating te array 
arr=np.array([1,2,3,4,5,6])

#### Indexing

In [13]:
# Array indexing is start with 0.
# Array indexing is call will be negative and positive also.
arr[0]

1

In [14]:
arr[5]

6

In [15]:
arr[-2]

5

### Slicing

In [16]:
# last number always exclusive
arr[0:2]

array([1, 2])

In [17]:
# Nan values always call all values in the array
arr[3:]

array([4, 5, 6])

In [18]:
arr[:3]

array([1, 2, 3])

In [19]:
arr[0:-3]

array([1, 2, 3])