### NUMPY-2-D-MATRIX-INDEXING-AND-SLICING

In [14]:
# import numpy 
import numpy as np

In [15]:
# creating 2d array
Matrix=np.array([[5,2,3],[23,56,66],[10,34,55]])

In [16]:
# find array type
Matrix.ndim

2

#### Indexing Using double brackets

In [17]:
Matrix[0][2]

3

In [18]:
Matrix[1][2]

66

In [19]:
Matrix[2][0]

10

#### Indexing Using Single brackets(Recommended)

In [20]:
Matrix[0,2]

3

In [21]:
Matrix[1,2]

66

In [22]:
Matrix[2,0]

10

#### Slicing using single Notation

In [23]:
Matrix

array([[ 5,  2,  3],
       [23, 56, 66],
       [10, 34, 55]])

In [24]:
Matrix[:2]

array([[ 5,  2,  3],
       [23, 56, 66]])

In [25]:
Matrix[:2,:2]

array([[ 5,  2],
       [23, 56]])