### NUMPY-VIEW-VS-COPY

In [12]:
# import numpy
import numpy as np

#### View

In [13]:
arr=np.array([1,2,3,4,5,6,6])

In [14]:
newarr=arr[0:3]
newarr

array([1, 2, 3])

In [15]:
newarr[ : ] = 0
arr

array([0, 0, 0, 4, 5, 6, 6])

#### Copy

In [16]:
newarr=arr[0:3].copy()
newarr

array([0, 0, 0])

In [17]:
newarr[ : ] = 0
arr

array([0, 0, 0, 4, 5, 6, 6])