### NUMPY-CONDITIONAL-SELECTION

In [7]:
# Import numpy libaray
import numpy as np

In [8]:
# Creating the array
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Apply the Condition 
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [10]:
# making mask of condition
mask=arr>4

In [11]:
# Call values by help of mask
arr[mask]

array([ 5,  6,  7,  8,  9, 10])

#### Even Numbers Finding using condition

In [12]:
# we use the reminder theorm for even numbers
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])