### NUMPY-ARRAY-OPERATION

In [7]:
#import numpy
import numpy as np

In [8]:
arr=np.arange(1,12)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
# Multiply all array values with 2
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [10]:
# Add 2 all array values in it 
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [11]:
# subtract 2 from all array values
arr -2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [12]:
# divide by 2 all values of an array
arr /2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [13]:
# power 2 of all array values
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])