### NUMPY-ARRAY-OPERATION-ON-TWO-OR-MORE-THEN-TWO-ARRAY

#### Note: The Shape of array in which you operation perform is to be same size

In [1]:
#import numpy
import numpy as np

In [2]:
# Creating two arrays 
arr1=np.array([2,6,5,4])
arr2=np.array([2,5,3,5])

In [3]:
# Addition of two arrays
arr1+arr2

array([ 4, 11,  8,  9])

In [4]:
# Substraction of two arrays
arr1-arr2

array([ 0,  1,  2, -1])

In [5]:
# Division of two arrays
arr1/arr2

array([1.        , 1.2       , 1.66666667, 0.8       ])

In [6]:
# Multiplication of two arrays
arr1*arr2

array([ 4, 30, 15, 20])

In [7]:
# Power of an array pn another array of two arrays
arr1**arr2

array([   4, 7776,  125, 1024])

In [8]:
# Mix operation  of two arrays
arr1+arr2-arr2*arr2

array([  0, -14,  -1, -16])