### SOME-MORE-FUCTIONS-OF-NUMPY

In [7]:
# Import Numpy
import numpy as np


In [8]:
# Creating the arrray 
arr=np.array([2,3,4,5,9,6,1])

In [9]:
# Finding the max value in the array
arr.max()

9

In [10]:
# Finding the max value in the array with position
arr.argmax()

4

In [11]:
# Finding the min value in the array
arr.min()

1

In [12]:
# Finding the min value in the array with position
arr.argmin()

6

In [13]:
np.sqrt(arr)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 3.        ,
       2.44948974, 1.        ])

In [14]:
np.exp(arr)

array([7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
       8.10308393e+03, 4.03428793e+02, 2.71828183e+00])

In [15]:
# Find all sin values of an array
np.sin(arr)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427,  0.41211849,
       -0.2794155 ,  0.84147098])

In [16]:
# Find all cos values of an array
np.cos(arr)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219, -0.91113026,
        0.96017029,  0.54030231])

In [17]:
# USing Linspace to creating the array
np.linspace(1,40,5)

array([ 1.  , 10.75, 20.5 , 30.25, 40.  ])

In [18]:
# Creating Bool Array
arr2=np.array([1,1,0,1],dtype="bool")
arr2

array([ True,  True, False,  True])