### NUMPY-AXIS

#### Rows=1 and Coloum=0

In [5]:
#Import Numpy
import numpy as np

In [6]:
# creating the matrix array
np.random.seed(212)
arr=np.random.randint(1,11,9).reshape(3,3)
arr

array([[ 9,  3,  5],
       [10,  2, 10],
       [ 4,  1,  1]])

In [7]:
#Finding the max value
arr.max()

10

In [8]:
#Finding the max value with Row=1
np.max(arr,axis=1)

array([ 9, 10,  4])

In [9]:
#Finding th min value with axis coloum=0
np.min(arr,axis=0)

array([4, 1, 1])

In [10]:
# Cumsum Function
arr.cumsum()

array([ 9, 12, 17, 27, 29, 39, 43, 44, 45])