### SHUFFLE-AND-UNIQUE

In [8]:
#import numpy
import numpy as np


In [9]:
# Creating the array 
np.random.seed(123)
arr=np.random.randint(1,15,15)
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [10]:
# Shuffle the array using the shuffle funtion
np.random.shuffle(arr)
arr


array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [11]:
# Finding the Unique values in the array
np.unique(arr)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [12]:
# How many unique item in this array
np.unique(arr).shape

(10,)

In [13]:
# Finding the locations and howmnay repeats
np.unique(arr,return_index=True,return_counts=True)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

#